### ISSUE TITLE
Error when running via wagi

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#1]
Following the docs to run bartholomew and I hit the following:

```
$ wagi -c modules.toml
No log_dir specified, using temporary directory /var/folders/5h/_7jqb5nn5fz7vfcc9zhwn7nc0000gn/T/.tmpK049o3 for logs
Error: Not all routes could be built: failed to read input file
```

Am I correct in assuming it is because of the following hardcoded path to the fileserver module in the [modules.toml file](https://github.com/technosophos/bartholomew/blob/main/modules.toml)?

```
[[module]]
module = "/Users/technosophos/Code/Grain/fileserver/fileserver.gr.wasm"
route = "/static/..."
volumes = {"/" = "static/"}
```

Wondering what the best approach is for updating the path/location per the host system?  I'm new to the [wagi](https://github.com/deislabs/wagi) project... can a module reference a hosted URI?  Or do they currently need to exist relative/locally to the host system?

**Comment by technosophos** [comment]
Yes, that path should go to the location of `fileserver.gr.wasm`. I need to update the docs.

**Comment by radu-matei** [comment]
The docs are updated, I think this can be closed now.
Feel free to reopen if the docs are not clear.

Thanks.
