### ISSUE TITLE
Align versions between bartholomew.wasm and bart CLI?

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#102]
Should we align versioning between the bartholomew.wasm module and the bart CLI?

Currently the former is at [0.3.0](https://github.com/fermyon/bartholomew/blob/main/Cargo.toml#L3) while the latter is at [0.1.0](https://github.com/fermyon/bartholomew/blob/main/bart/Cargo.toml#L3).

Confusion can result since both are currently included as artifacts for a given release of this repo, eg [v0.3.0](https://github.com/fermyon/bartholomew/releases/tag/v0.3.0), yet the bart CLI will give a different version.  So, when a user is checking their CLI version to see if it is the latest, the signal is muddied.

**Comment by karthik2804** [comment]
I agree, I think we should align the versions of `bartholomew.wasm` and `bart` CLI.

**Comment by radu-matei** [comment]
Addressed by #105.
