### ISSUE TITLE
ci/cd: automate checksum generation on release

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#106]
Let's update the current [release workflow](https://github.com/fermyon/bartholomew/blob/main/.github/workflows/release.yml) to add automated generation of the checksums file which we can include on the created GH release.

Then we can slim down the [release process doc](https://github.com/fermyon/bartholomew/blob/main/release-process.md).

**Comment by radu-matei** [comment]
That would be excellent!

@karthik2804 — is this something you would be interested to look at?
