### ISSUE TITLE
Spin compatibility: remove wasi-experimental-http

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#109]
Spin removed support for wasi-experimental-http in https://github.com/fermyon/spin/pull/699.

I believe Bartholomew needs to do the same for compatibility with Spin.

(To be clear, the last v0.4.0 release of Spin _is_ compatible)

For instance, when I try to run the docs site with Spin built from HEAD, I see:

```
$ spin -V
spin 0.4.0 (232567f 2022-08-22)

$ spin up
Error: unknown import: `wasi_experimental_http::close` has not been defined
Error: exit status: 1
```

**Comment by vdice** [comment]
Actually, I may have this wrong.  I don't see Bartholomew using wasi-experimental-http directly, it is just in the Cargo.lock.  Perhaps what is necessary is to bump the spin SDK version?

**Comment by karthik2804** [comment]
I just tested it and the SDK version is not causing it. It is a dependency `handlebars-sprig` which causes this. Downgrading that to `v0.2.0` solves this. 

`v0.3.0` introduced the `tweets` and `gists` functions which rely on `wasi_experimental_http`. I am not sure what the approach towards this must be.

**Comment by vdice** [comment]
Thanks for checking this out, @karthik2804.  Interesting... would we lose functionality if we go with the v0.2.0 downgrade?

**Comment by rajatjindal** [comment]
i had been working on a branch to fix it. but don't have a fix for it right now. v0.3.0 was working fine with `Bartholomew` when we released it first. i am not too sure why it stopped working

downgrading to v0.2.0 will lose tweets/gists embedding functionality. we can downgrade until we can fix it?

**Comment by karthik2804** [comment]
It doesn't work because one of the latest commits to spin removed support for `wasi-experimental-http` (https://github.com/fermyon/spin/pull/699) as mentioned in the OP. It will still work with Bartholomew when using spin built from a commit prior to that.

**Comment by radu-matei** [comment]
Yeah, we don't need to remove functionality — rather than using the bespoke `wasi_experimental_http` crate, it can use the Spin SDK directly, or import `wasi_outbound_http` from Spin.

**Comment by rajatjindal** [comment]
I was able to get it working with spin sdk, but not able to publish new release as it needs a released version of spin-sdk.

Is that something we can do @radu-matei ?

I will spend more time on it tomorrow and will try to get a release pushed (worst case try to implement outbound http in handlebars sprig repo).

Thank you everyone for the inputs.

**Comment by karthik2804** [comment]
@rajatjindal can we not just switch from using a release of handlebars-sprig in Bartholomew to using a `git` as a source in the dependancy?

**Comment by rajatjindal** [comment]
We can, i was just not sure of it will be acceptable.

If the team is ok with that, i am happy to open pr for it.

**Comment by radu-matei** [comment]
That definitely works, @rajatjindal!
Thank you!
