### ISSUE TITLE
Configuration settings - documentation update

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/bartholomew#114]
A recent note from @karthik2804 spoke about config.

"The enable_shortcodes is defined only on each .md file but not in the site.toml file. The corresponding entry in the code block above needs to be deleted as well. Those entries actually belong on markdown.md."

I believe this means removing the following lines from the site's overall configuration documentation (the `configuration.md`)

<img width="1034" alt="Screen Shot 2022-08-26 at 3 47 52 pm" src="https://user-images.githubusercontent.com/9831342/186831264-9439acdb-68b1-48c1-9a33-047e7451ccfd.png">

I am then wondering should the above configuration then be added to the `markdown.md`'s page where the TOML is mentioned for pages and posts. Not 100% sure, @karthik2804 perhaps you can chime in.

Also if there are any other config related changes, please let me know and we can do a single PR for config.

Thank you
Tim

**Comment by karthik2804** [comment]
Thanks, @tpmccallum. I will take a look at the docs to find out if there are any other changes required.

**Comment by karthik2804** [comment]
closed with #127
