### ISSUE TITLE
Gluon

### ISSUE THREAD

**Issue by ShalokShalom** [fermyon/bartholomew#128]
Considering it is embeddable in Rust, can I use Gluon instead of Rhai?

https://github.com/gluon-lang/gluon

**Comment by karthik2804** [comment]
I don't think this would be currently possible as currently, [handlebars](https://crates.io/crates/handlebars) does seem to support only rhai scripts as the supported language for scripting.

**Comment by ShalokShalom** [comment]
So, there needs to be specific support?
Why?

**Comment by itowlson** [comment]
"Why" is a question for the Handlebars folks, really **grin** - my guess is that nobody has yet asked for Gluon support or sent them a PR for it.

The Handlebars scripting implementation seems to be around https://github.com/sunng87/handlebars-rust/blob/08f2df78b768f97bc45689ecaf610a8eccf6eb20/src/registry.rs#L412 and in https://github.com/sunng87/handlebars-rust/blob/master/src/helpers/scripting.rs if you're interested in talking to the Handlebars folks about adding Gluon.
