### ISSUE TITLE
Bart CLI does not build on Windows

### ISSUE THREAD

**Issue by tpmccallum** [fermyon/bartholomew#129]
When cloning & building the Bartholomew Command Line Interface (CLI) on Windows, using the `make bart` command, the following error is encountered.

```bash
error LNK2019: unresolved external symbol __imp_wasi-outbound-http_request referenced in function
error LNK2019: unresolved external symbol __imp_outbound-pg_query referenced in function
error LNK2019: unresolved external symbol __imp_outbound-pg_execute referenced in function
3 unresolved externals
error: linking with `link.exe` failed: exit code: 1120
```
Had a chat with @itowlson (thanks Ivan) and it appears that we could/should take Bartholomew functionality which is fundamentally designed to compile to Wasm (any features intended to be used within Spin) and create a new `[server]` feature set in Bartholomew source code.

The separation of these features will allow the implementer of Bartholomew server to specify the use of the `[server]` feature set when building the `Bartholomew.wasm`. But will also allow the user of the CLI to build the CLI (without the CLI build process linking features not essentially to the CLI's intended operation).

Hope this makes sense.

Once this is done, we can go ahead and build the binary executable for Windows and close out https://github.com/fermyon/bartholomew/issues/94 as well.

Please let me know if you need any more error messages or info.

**Comment by itowlson** [comment]
@karthik2804 I know you've been working on Bartholomew - would you be interested in tackling this and do you have availability?  The underlying issue is breaking the CLI's indirect dependency on the Spin SDK.

**Comment by karthik2804** [comment]
@itowlson I will be happy to take a shot at this issue.

**Comment by itowlson** [comment]
Appreciate it @karthik2804, thanks so much!

**Comment by tpmccallum** [comment]
This is fixed in PR https://github.com/fermyon/bartholomew/pull/130
