### ISSUE TITLE
Too many open files when load testing

### ISSUE THREAD

**Issue by radu-matei** [fermyon/bartholomew#14]
Attempting to load test Bartholomew results in an IO error because of the too many files opened:

```
$ make serve
Ready: serving on 127.0.0.1:3000
Jan 09 22:24:35.879 ERROR hyper::server::tcp: accept error: Too many open files (os error 24)
```

```
$ bombardier http://localhost:3000/blog
Bombarding http://localhost:3000/blog for 10s using 125 connection(s)

  Errors:
       timeout - 77
    dial tcp 127.0.0.1:3000: connect: connection reset by peer - 25
    the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection - 22
    write tcp 127.0.0.1:58154->127.0.0.1:3000: write: broken pipe - 1
```

The actual Hyper error doesn't happen all the time, but the increased latency is noticeable even with fewer concurrent connections.

(Update: this might also be an issue with my local setup, which might very well be the case, I'm getting all sorts os weird errors after an update...)

**Comment by technosophos** [comment]
So say you have 125 connections simultaneously hit Bartholomew, and you have 100 files in your Bartholomew. If Wasm opens every file using preopen, then you would have 12500 file handles created right away. What's your current limit on number of open files?

Bartholomew does currently do a LOT of file I/O onload, too, so you could definitely be hitting limits fast

**Comment by radu-matei** [comment]
This has been fixed by improvements to Wagi (and by potentially increasing the open files limit for the process).
