### ISSUE TITLE
Issue reading content

### ISSUE THREAD

**Issue by cohix** [fermyon/bartholomew#143]
`spin 0.6.0 (12a5037 2022-10-21)`

I followed the quickstart guide, and after adding my first post, I load the page and get this in the browser:

`Rendering "/content/blog/hello.md": Capabilities insufficient (os error 76)`

Same message in the spin logs

It can load `index.md` just fine.

Halp :)

**Comment by karthik2804** [comment]
Are you using the latest Bartholomew version? This was an issue due to writing to a cache file which has now been fixed.

**Comment by cohix** [comment]
@karthik2804 I used the template repo in the bartholomew quickstart... what's the easiest way to build the latest bartholomew?

**Comment by karthik2804** [comment]
@cohix You can grab the latest binary from the releases https://github.com/fermyon/bartholomew/releases/tag/v0.6.0 or you can build from the source by building this repo.

**Comment by cohix** [comment]
That did the trick! Thanks @karthik2804
