### ISSUE TITLE
make bart:  make: *** [bart] Error 1

### ISSUE THREAD

**Issue by cloudjumper2000** [fermyon/bartholomew#153]
Following your guide on MacOS fails: 
https://bartholomew.fermyon.dev/quickstart

$ git clone https://github.com/fermyon/bartholomew.git
$ cd bartholomew
$ make bart

This last step 'make bart' errors with output:
cargo build --release --manifest-path=bart/Cargo.toml
make: cargo: No such file or directory
make: *** [bart] Error 1

**Comment by vdice** [comment]
Hi @cloudjumper2000, thank you for filing.  It looks like we're missing a step to [install cargo](https://doc.rust-lang.org/cargo/getting-started/installation.html) if not already on the system.  Can you install cargo when you have a chance and then assuming that's the issue, we can update the docs?

**Comment by cloudjumper2000** [comment]
Hi @vdice, i installed cargo but that didnt seem to resolve the issue even after coping the bart folders as noted:
```
(NOTE: target/release/bart will need to be installed to a user executable directory such as /usr/local/bin/ to be run when built this way.)
```
Reread a bit and gave this a try:
Downloaded bart from [here](https://github.com/fermyon/bartholomew/releases/). Added it to /usr/local/bin/, opened a new terminal and added it to security and privacy... that worked. 

```
MB % bart
bart 0.6.0
The Bartholomew CLI
...
```

Thanks for the quick response, Cheers!

**Comment by vdice** [comment]
@cloudjumper2000 glad to hear the pre-built binary approach is working for you.  Happy to help troubleshoot building from source when/if the need arises.

I've submitted https://github.com/fermyon/bartholomew/pull/154 adding a link and mention of cargo.  Closing this one for now.  Thanks again for raising.
