### ISSUE TITLE
"Operation not permitted" (Mac OS error 63) unless `--allow-transient-write`

### ISSUE THREAD

**Issue by itowlson** [fermyon/bartholomew#175]
Reported by @kingdonb (https://github.com/fermyon/spin-vscode/issues/34#issuecomment-1628840713, slightly edited from original post):

> I've been working from https://github.com/coderoflagos/bartholomew-sample
> 
> I haven't modified this repo at all, only cloned it. My machine is a MacOS M1 Ventura 13.4.1, and my partner in crime (wife with the blog) is running Windows 10 without WSL. (There is a WSL installed in case it is needed, but we aren't using it.)
> 
> If I run `spin up` then I get:
> 
> ```
> $ spin up
> Logging component stdio to ".spin/logs/"
> Preparing Wasm modules is taking a few seconds...
> 
> 
> Serving http://127.0.0.1:3000
> Available Routes:
>   bartholomew: http://127.0.0.1:3000 (wildcard)
>   fileserver: http://127.0.0.1:3000/static (wildcard)
> Request path: /index
> Base URL: Some("http://localhost:3000")
> scripts: registering get_page
> scripts: registering blogs
> Path /content/index.md
> Skipping dotfile "/content/.DS_Store"
> Skipping dotfile "/content/blog/.DS_Store"
> Handler returned an error: Rendering "/content/index.md": Operation not permitted (os error 63)
> Request path: /favicon.ico
> Base URL: Some("http://localhost:3000")
> scripts: registering get_page
> scripts: registering blogs
> Path /content/favicon.md
> Skipping dotfile "/content/.DS_Store"
> Skipping dotfile "/content/blog/.DS_Store"
> Handler returned an error: Operation not permitted (os error 63)
> $ spin --version
> spin 1.3.0 (9fb8256 2023-06-12)
> ```
> 
> On the web page, we get:
> 
> ```
> Rendering "/content/index.md": Operation not permitted (os error 63)
> ```
> 
> I can confirm that the issue resolves when I run `spin up --allow-transient-write`
> 
> These are the file permissions in case it matters:
> 
> ```
> $ ls -l content/
> total 16
> drwxr-xr-x  5 kingdonb  staff  160 Jul  9 12:39 blog/
> -rw-r--r--  1 kingdonb  staff  247 Jul  9 12:39 blog.md
> -rw-r--r--  1 kingdonb  staff  911 Jul  9 12:39 index.md
> ```

**Comment by karthik2804** [comment]
This is due the caching behavior. It looks like an older version of `bartholomew` that was not tolerant but the later versions should be. 

It just needs an updated version of `bartholomew`.

**Comment by itowlson** [comment]
Ah yep, I see it.  The sample embeds a Bartholomew Wasm module (https://github.com/coderoflagos/bartholomew-sample/blob/5bb44beac88d0d673ac07931c610eae8472a94d3/spin.toml#L8) and it's probably fairly old by now.  @kingdonb please try overwriting `modules/bartholomew.wasm` with the one from https://github.com/fermyon/bartholomew/releases/tag/v0.8.0, or replacing the line with a URL reference a la

```
source = { url = "https://github.com/fermyon/bartholomew/releases/download/v0.8.0/bartholomew.wasm", digest = "sha256:ad5ac6215fb67ca122011d2d12840cb69ba80819499641349e92c05ceb65afc1" }
```

**Comment by kingdonb** [comment]
Confirm, removing the modules from the committed sources and changing them to a reference to the latest version, with digest for authenticity, apparently solves that issue. Sorry for the bogus report!

**Comment by itowlson** [comment]
Nah, thanks for flagging it!  I've raised a PR to the original sample repo.  I'll close this now this bit is working for you (do reopen if needed of course).
