### ISSUE TITLE
"trim" template functions

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#25]
Per @rajatjindal's suggestion, it would make a lot of sense to implement the [Sprig functions](https://masterminds.github.io/sprig/) for Bartholomew. Rather than file an issue for each function, I figured I'd break these down into small batches. (Note: I am not entirely sure all of the functions can be done with the same syntax. I am no pro in writing the Handlebars functions.)

- [ ] `trim STRING` removes whitespace off both sides of the string
- [ ] `trim_all SUBSTRING STRING` trim `SUBSTRING` from both sides of the string. Example: `trim_all "$" "$4.00$"` should return `"4.00"`
- [ ] `trim_suffix SUFFIX STRING` trim `SUFFIX` string off of the back of a string.
- [ ] `trim_prefix PREFIX STRING` trims `PREFIX` from the front of the string

**Comment by rajatjindal** [comment]
while i am implementing these, i am realizing that it may become hard to manage all template functions in single `template.rs`

do you think it might make sense to implement them in separate `module` (sorry my rust terminology is still rusty) or repo?

**Comment by rajatjindal** [comment]
these are now added to `handlebars_sprig` lib

**Comment by technosophos** [comment]
Closed when we upgraded to the latest handlebars_sprig!
