### ISSUE TITLE
String transformation template functions

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#26]
Per #25, implement the [Sprig functions](https://masterminds.github.io/sprig/) for Bartholomew. Rather than file an issue for each function, I figured I'd break these down into small batches. (Note: I am not entirely sure all of the functions can be done with the same syntax. I am no pro in writing the Handlebars functions.)

- [ ] `title STRING` changes string to `Title Case`
- [ ] `untitle STRING` removes title casing: `HELLO World` becomes `hELLO world` (Not sure if we want this one)
- [ ] `repeat COUNT STRING` repeat the string `COUNT` number of times
- [ ] `substr START END STRING`. Given a string, start at index START and capture a string that ends at END
- [ ] `nospace STRING` removes internal spaces from a string. ` h e l l o ` becomes `hello` (Not sure if we want this one)
- [ ] `abbrevboth LEFT_OFFSET MAX_LEN STRING` offsets LEFT_OFFSET from the left, and then truncates the string to MAX_LEN, using `...` on both sides. (The sprig docs [explain this a little better](https://masterminds.github.io/sprig/strings.html))
- [ ] `initials STRING` take the first letter from each word in a string, and return those letters as a string: `Hello World` becomes `HW`
- [ ] `camel_case`, `snake_case`, `kebab_case` and `swap_case` were all useful in Sprig... optional to implement here, too

**Comment by karthik2804** [comment]
closed by #133
