### ISSUE TITLE
Random template functions

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#27]
Per #25, implement the [Sprig functions](https://masterminds.github.io/sprig/) for Bartholomew. Rather than file an issue for each function, I figured I'd break these down into small batches. (Note: I am not entirely sure all of the functions can be done with the same syntax. I am no pro in writing the Handlebars functions.)

Extra warning: I don't know if I've ever tried using random functions within WASI.

- `rand_alpha`  Random from set [a-zA-Z]
- `rand_numeric` Random from set [0-9]
- `rand_alphanum` Random from set [a-zA-Z0-9]

**Comment by karthik2804** [comment]
Closed by #133
