### ISSUE TITLE
Add gzip content encoding

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#3]
Can we add an option to support `Content-Encoding` with `gzip` support?

This shouldn't require a change to Wagi. But it might require a fairly major rewrite of Bartholomew. Instead of printing directly to STDOUT, we'd have to print to an output stream that is wrapping a gzip writer. Then we would have to flush the gzip writer to stdout.

We'd also have to write the extra `Content-Encoding: gzip` header.

**Comment by rajatjindal** [comment]
i am trying my hands on this

**Comment by rajatjindal** [comment]
I worked on  this, and i am quite certain we need to change `wagi` for it. 

the function `compose_response` is corrupting the response body/headers.  

stay tuned while i am working on a PR to fix it.

**Comment by rajatjindal** [comment]
ok, i take it back. i was able to fix it within `bartholomew`. Now need to expose `gzip` as an option and open the PR . will continue tomorrow.
