### ISSUE TITLE
Math template functions

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#30]
Per #25, implement the [Sprig functions](https://masterminds.github.io/sprig/) for Bartholomew. Rather than file an issue for each function, I figured I'd break these down into small batches. (Note: I am not entirely sure all of the functions can be done with the same syntax. I am no pro in writing the Handlebars functions.)

Some math functions that we could implement. Not sure if we need int and float variants, or if the JSON numeric type works

- [x] `add`
- [ ] `add1`
- [x] `sub`
- [x] `mul`
- [x] `div`
- [x] `mod`
- [x] `max`
- [x] `min`
- [x] `floor`
- [x] `ceil`
- [x] `round`
- [x] `randInt`

**Comment by rajatjindal** [comment]
all except `randInt` are done.

**Comment by rajatjindal** [comment]
`randInt`  added to `handlebars_sprig` crate and will be available with next update of the same in `bartholomew`.

this  issue  can be closed.

**Comment by radu-matei** [comment]
reference — https://github.com/rajatjindal/handlebars-sprig/blob/main/src/math.rs

Thank you so much for implementing this, @rajatjindal!
