### ISSUE TITLE
numeric list functions

### ISSUE THREAD

**Issue by technosophos** [fermyon/bartholomew#31]
Per #25, implement the [Sprig functions](https://masterminds.github.io/sprig/) for Bartholomew. Rather than file an issue for each function, I figured I'd break these down into small batches. (Note: I am not entirely sure all of the functions can be done with the same syntax. I am no pro in writing the Handlebars functions.)

- [ ] `until COUNT` generate a list of integers from 0 to COUNT.
- [ ] `until_step COUNT STEP` generate a list of integers from 0 to COUNT incrementing by STEP
- [ ] `seq` described [here](https://masterminds.github.io/sprig/integer_slice.html) OPTIONAL... not sure we need it. Or maybe we need this and not `until`...

**Comment by karthik2804** [comment]
Closed with #133
