### ISSUE TITLE
Create a Bartholomew CLI

### ISSUE THREAD

**Issue by radu-matei** [fermyon/bartholomew#45]
It would be very helpful to have a CLI that simplifies working with Bartholomew projects.
Specifically, it would contain functionality for:

- creating new sites
- creating new posts
- listing and displaying the content and a post calendar (see https://github.com/fermyon/bartcal)

I started implementing the latter two features, here is the current state:

```
 ➜ bart calendar ./content
Wed, Dec 22, 2021 - 'Documentation' index.md
Thu, Dec 23, 2021 - 'First Post!' 2021-12-23-first-post.md
Thu, Dec 23, 2021 - 'What Is Markdown?' 2021-12-23-what-is-markdown.md
Thu, Dec 23, 2021 - 'Markdown examples' markdown.md

 ➜ bart new post content/blog --author "Radu Matei" --template abc --title "Writing a new post using Bart"
Wrote new post in file content/blog/untitled.md
```

If this looks good, I will open a PR soon.

**Comment by technosophos** [comment]
I will literally use this _every day_.
