### ISSUE TITLE
Document the CLI a bit more

### ISSUE THREAD

**Issue by comradelemoncake** [fermyon/bartholomew#60]
The information on using the CLI doesn't really show people how to actually use and install the CLI. I can take a stab at it also once there's a broader discussion.

**Comment by tpmccallum** [comment]
This is attended to in https://github.com/fermyon/bartholomew/pull/110
Please feel free to close this, once 110 is merged, if you like.
<img width="1150" alt="Screen Shot 2022-08-24 at 5 10 55 pm" src="https://user-images.githubusercontent.com/9831342/186354210-9e37a307-ef2b-40a4-a4c7-7ebcf46b501f.png">
