### ISSUE TITLE
Can't compile Bart on Ubuntu 20.04 WSL

### ISSUE THREAD

**Issue by comradelemoncake** [fermyon/bartholomew#61]
Getting a really annoying compilation error when trying to compile Bart on Ubunto 20.04 WSL:

Command: 

```
jdbohrman@DESKTOP-HSLE200:~/fermyon.com/content/blog$ cargo build --release
...
   Compiling toml v0.5.8
   Compiling handlebars v4.2.2
   Compiling handlebars_sprig v0.3.0
   Compiling bartholomew v0.2.0 (/home/jdbohrman/bartholomew)
...
error: linking with `cc` failed: exit status: 1

         collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `bartholomew` due to previous error
```

I've tried installing things like `build-essential` and `gcc-multilib` to no avail.

**Comment by radu-matei** [comment]
Could you please share the entire command you used for building?
Thanks!

**Comment by comradelemoncake** [comment]
@radu-matei Updated the original comment!

**Comment by radu-matei** [comment]
There are two projects in this repository:

- Bartholomew, which ends up being compiled as a WebAssembly module and run by Spin
- the Bartholomew CLI, which is a native binary.

To compile the CLI, you need to compile the project from the `bart/` directory:

```
$ cargo build --release --manifest-path=bart/Cargo.toml
```

Alternatively, you can run the `make bart` command.

**Comment by tpmccallum** [comment]
The documentation has now been updated to reflect how to install the `bart` CLI and also the Bartholomew WebAssembly module.
