### ISSUE TITLE
CI: update bart cli release asset

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#64]
Currently the [bart cli release asset](https://github.com/fermyon/bartholomew/releases/tag/v0.3.0) is for linux amd64 but its name doesn't signify this.  Consider updating the name to add the arch extension... and perhaps add other arch combos 😉

**Comment by vdice** [comment]
@karthik2804 and I are thinking of tackling this when we add support for Mac and Windows CLIs, either via cross-compilation or via build hosts.

**Comment by tpmccallum** [comment]
The bart cli release section has been updated with Linux, macOS and Windows. We compressed each of the `bart` files and named them accordingly and then also performed the `shasum` and also added those checksum values to the checksum test file.

I was just not able to build on macos-aarch64 for now. Perhaps we can look at that one also down the track.

For now the naming convention on all of the files (using separate architecture) and the hashing is all sorted.
