### ISSUE TITLE
Improve support for relative links in Markdown content

### ISSUE THREAD

**Issue by dicej** [fermyon/bartholomew#69]
Per the discussion in https://github.com/fermyon/spin/pull/426, Bartholomew currently has trouble with relative links in Markdown content.  Making them non-relative fixes Bart but breaks browsing those links in GitHub and elsewhere, whereas making them relative fixes GitHub browsing but breaks Bart.

Therefore, Bart should handle relative links correctly, translating them to the appropriate HTML URIs automatically instead of expecting a certain format in the source Markdown file.

**Comment by technosophos** [comment]
I had hoped that if we got #55 done, we would be able to do something like `{{ link "/foo/bar" }}` and have that generate the full href. But there might be a way to override the generator function for the markdown parser and capture `[foo](/bar)` and then translate those to full URLs.

**Comment by dicej** [comment]
@radu-matei What do you think of the following?

Modify [Content::render_markdown](https://github.com/fermyon/bartholomew/blob/875106be47a4362c903bc40859cc3a750fab35dd/src/content.rs#L184-L186) to preprocess relative links (e.g. transform ./http-trigger.md into /http-trigger) prior to translating to HTML.  This has the advantage of preserving the existing URI format (i.e. https://spin.fermyon.dev/http-trigger/ stays as it is and does not become https://spin.fermyon.dev/http-trigger.md, which would be confusing since the page is HTML -- not Markdown -- once it's been rendered).

Ideally, we could hook into pulldown-cmark's `push_html` function and do the link translation during HTML rendering, ~~but it doesn't look like that's possible without forking pulldown-cmark~~, and I don't know if performance is a concern anyway.

Edit: Nevermind, I just noticed `push_html` takes an iterator of `Event`s, so we can just map that iterator with a function that translates links.  I can make a PR if that sounds good.
