### ISSUE TITLE
Make/cargo build issue

### ISSUE THREAD

**Issue by vdice** [fermyon/bartholomew#75]
I'm seeing the following when I run `make` in this project:
```
$ make
cargo build --target wasm32-wasi --release
error: failed to parse manifest at `/Users/vdice/go/src/github.com/fermyon/bartholomew/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
make: *** [build] Error 101
```

Not sure if an update/upgrade to my local rust/cargo env is necessary -- or if an update to this project's Makefile/Cargo.toml is due.

**Comment by vdice** [comment]
I got it working/building after I ran the following on my machine:

```
$ rustup install nightly
$ rustup default nightly
```

If this is the correct solution, should we add something to the docs?

**Comment by rajatjindal** [comment]
I ran into this today as well. we should document this in README.

**Comment by rajatjindal** [comment]
i had to also add `-f docs/spin.toml` to Makefile's  `serve` target to get the site up and running.

**Comment by vdice** [comment]
As of writing when building at the HEAD commit of this repo, I no longer appear to need to switch to `nightly`.  Are you seeing the same @rajatjindal ?  If so, we should be able to close this one out.

**Comment by radu-matei** [comment]
I also don't need to use Rust Nightly.

Closing, but feel free to reopen if this is still an issue.
Thanks!
