### ISSUE TITLE
minor - REadme.md has a broken link 'bartholomew-screenshot.png'

### ISSUE THREAD

**Issue by VishnuJin** [fermyon/bartholomew#77]
The 'fermyon/bartholomew' repository doesn't contain the 'static/bartholomew-screenshot.png' path in 'main'.

**Comment by technosophos** [comment]
See also: https://twitter.com/GeoffreyWiseman/status/1541483479669563400?s=20&t=rErjiqocogpXk6_ex8JpDg

**Comment by vdice** [comment]
It looks like the `static` folder at root was removed in https://github.com/fermyon/bartholomew/commit/e91277002fa7efaee805a599fa595d63456ac637

Do we want to add some or all of the contents back to `static` at the root-level?  Note that the current version of the [README](https://github.com/fermyon/bartholomew#readme) (and ability to `spin up` or `make serve` of the site from the root-level `spin.toml`) depends on this directory as well.

Or do we just want to update the README with steps to bring up the bartholomew docs site in `docs`?

cc @radu-matei

**Comment by tpmccallum** [comment]
Please note that there is a new PR which updates the README.md file with a new screen capture and link to official docs (as well as some new documentation about the difference between installing the server and the bart CLI.)

https://github.com/fermyon/bartholomew/pull/93

It would be great to merge the 93 PR and close this issue. In saying that, I would also like to discuss the idea of reducing the amount of information in the README.md to a minimum i.e. just a quick intro and description and then a single link to official documentation (a single source of truth i.e. https://bartholomew.fermyon.dev/) whereby we only ever have to update one documentation location moving forward. Kind of like how Spin README.md is quite minimalistic in terms of technical documentation and usage guides and then just primarily points to [spin.fermyon.dev](https://spin.fermyon.dev/).

**Comment by vdice** [comment]
Closed by https://github.com/fermyon/bartholomew/pull/93; thank you @tpmccallum!  I'm in favor of the simplifications mentioned above 👍
