### ISSUE TITLE
Cross platform release binaries

### ISSUE THREAD

**Issue by radu-matei** [fermyon/bartholomew#94]
We currently have a `bart` CLI release binary for Linux — we need to add for Windows and macOS as well.

**Comment by tpmccallum** [comment]
Hi @radu-matei 
Just a quick question, if we go ahead and create the Windows and macOS executable binary files for the `bart` CLI the binary files will have the same name i.e. `bart`.
Shall we create a compressed file for each platform i.e. `bart-v0.4.0-macos-amd64.tar.gz`, `spin-v0.4.0-windows-amd64.zip` in the same manner that we do for Spin?
If so I can go ahead and create these and then update the release if the above approach is suitable.

**Comment by tpmccallum** [comment]
I see that perhaps @vdice and @karthik2804 may be planning to resolve this already over on issue https://github.com/fermyon/bartholomew/issues/64

**Comment by vdice** [comment]
> Shall we create a compressed file for each platform i.e. bart-v0.4.0-macos-amd64.tar.gz, spin-v0.4.0-windows-amd64.zip in the same manner that we do for Spin?

@tpmccallum indeed, this is the approach I was thinking of.  No one yet owns this work, so it is up for grabs!

**Comment by tpmccallum** [comment]
Great, I will got this sorted next and keep the updates coming in the comments here.

**Comment by tpmccallum** [comment]
The https://github.com/fermyon/bartholomew/releases/tag/v0.4.0 section has been updated in the follow way.

**Linux**
- the Linux `bart` file has been compressed into `bart-cli-v0.4.0-linux-amd64.tar.gz`
- a `shasum -a 256` for `bart-cli-v0.4.0-linux-amd64.tar.gz` has been added to the checksum text file

**macOS**
- a new macOS `bart` file has been created
- the macOS `bart` file has been compressed into `bart-cli-v0.4.0-macos-amd64.tar.gz`
- a `shasum -a 256` for `bart-cli-v0.4.0-macos-amd64.tar.gz` has been added to the checksum text file

<img width="902" alt="Screen Shot 2022-09-14 at 3 28 52 pm" src="https://user-images.githubusercontent.com/9831342/190067016-e9c70bca-5990-4672-8291-cebfad3301f0.png">

**Windows**
The windows binary executable encountered an error when building. 
The following GitHub issue will resolve the error on Windows https://github.com/fermyon/bartholomew/issues/129

Once #129 is resolved, we can create the `bart-cli-v0.4.0-windows-amd64.zip`, update the checksum.txt file and close out this issue. 

Thanks
Tim

**Comment by karthik2804** [comment]
Are we also looking to add a macos-aarch64 build?

**Comment by tpmccallum** [comment]
I am not able to add macos-aarch64 at this stage unfortunately :(

However, after the fix relating to Windows, we have the following results.

![Screen Shot 2022-09-15 at 1 09 54 pm](https://user-images.githubusercontent.com/9831342/190304993-1be066e7-7357-4203-b043-0ad33b51a16f.png)

**Comment by tpmccallum** [comment]
Linux, macOS and Windows have all been tested.
Also the new bartholomew.wasm file has been tested (added to bartholomew-site-template locally and also added to fermyon.com locally; in each respective `modules` directory).
