### ISSUE TITLE
Doc: Doc website ahead of current release

### ISSUE THREAD

**Issue by karthik2804** [fermyon/bartholomew#99]
The documentation website contains information about features not part of the current release (eg) themes, and request headers in the template.  There are currently no breaking changes. Should a new release be created?

**Comment by vdice** [comment]
Ah, good point @karthik2804.  I was on autopilot in deploying the docs.

We could go either way.  I think it'd be great to get a new release out.  Alternatively, or even if we want to in the short-term, I/we can redeploy the docs site on a previous commit.

**Comment by karthik2804** [comment]
@vdice, I feel like waiting for #91 and #98 before a new release might be a good idea.

**Comment by vdice** [comment]
👍 Okay, re-deployed https://bartholomew.fermyon.dev from https://github.com/fermyon/bartholomew/commit/330a5b861270b582f844d9364e54cf7e059e7e1c
